// Generated by CoffeeScript 2.5.1
(function() {
  var cube, print, square;

  square = function(x) {
    return x * x;
  };

  cube = function(number) {
    square(number) * number;
    return console.log("done cubing");
  };

  print = function(string) {
    return console.log(string);
  };

}).call(this);
